### ISSUE TITLE
BSXPCMessage received error for message: Connection interrupted

### ISSUE THREAD

**Issue by fvvliet** [softwarebrauerei/SobrCameraView-ios#1]
Hello SoftwareBrauerei,

I sometimes receive the following message in XCode when testing with the SobrCameraView : 
"BSXPCMessage received error for message: Connection interrupted"

Any suggestions how I can fix this ?
Thanks,
Frank

**Comment by katunch** [comment]
Hi Frank

Got the same "Error". I get the error in [IPDFCameraViewController](https://github.com/mmackh/IPDFCameraViewController) too. 
I suspect this message shows up only while you are connected to the debugger. We are using this pod in a productive app for a couple of weeks now and we did not get any crash reports about this.
