### ISSUE TITLE
Errors in XCode 7

### ISSUE THREAD

**Issue by fvvliet** [softwarebrauerei/SobrCameraView-ios#3]
In XCode7 I get quite a lot of errors in SobrCameraView.swift. Any plans to update ?

Thanks
Frank

**Comment by katunch** [comment]
Hi Frank, atm it isn't updated to Swift 2.0. At the moment there aren't any plans to upgrade it, because there are several solutions which are already upgraded. Nevertheless feel free to open a pull request.

**Comment by colasbd** [comment]
Hi, what do you mean by "there are several solutions which are already upgraded"?

**Comment by michaelbina** [comment]
What are the other solutions?  I can't seem to find any other similar libraries in swift...

**Comment by fvvliet** [comment]
@michaelbina : I switched back to IPDFCameraViewController (in ObjC). Compiles fine in XCode7.

**Comment by michaelbina** [comment]
What was the point of creating this library as an alternative to IPDFCameraViewController if its not going to be updated?

**Comment by katunch** [comment]
Pod updated to version 0.2.0. Example is working now with Xcode 7.1.1

**Comment by fvvliet** [comment]
Thanks @katunch !
