### ISSUE TITLE
ERROR: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by greaseham** [softwarebrauerei/SobrCameraView-ios#4]
When running on iOS 9.2 on iPhone 6 I randomly get an unwrapping error at line 252. I can see from debug that my image is passed into the completion handler but it would appear that self.biggestRectangle can return nil. Any suggestions?

**Comment by mrosenfield** [comment]
I am having a similar problem with iOS 9.1 on iPhone 6s.

**Comment by katunch** [comment]
will the issue be fixed if you replace line `252` with this code? 

```
completion(image: image, feature: self.biggestRectangle(SobrCameraView.highAccuracyRectangleDetector.featuresInImage(enhancedImage) as! [CIRectangleFeature]))
```

**Comment by MichelClement** [comment]
I'm having the same unwrapping error at line 252. But with katunch's fixed line it works till now. Btw. katunch, superb work!

**Comment by runeb** [comment]
Is it possible to do a version bump for this fix?

**Comment by katunch** [comment]
Did a version bump to cocoa pods
