### ISSUE TITLE
Saving Documents

### ISSUE THREAD

**Issue by xkenpachi** [softwarebrauerei/SobrCameraView-ios#5]
Hi, thanks for the example code. 

Is there anyway to add codes for saving documents as pdf? or must i have add the share button etc.

**Comment by katunch** [comment]
Hey @xkenpachi 

It's not that simple "to create a pdf". Because there are a few options you have to specifiy. Like the paper size etc. So that's why the camera view returns an UIImage. 

So feel free to implement it by yourself..

**Comment by xkenpachi** [comment]
Oh! Thank you very much for reply @katunch
